# Generated by Django 4.1.7 on 2023-02-25 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_alter_article_id_alter_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="arTicle_auThor_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="arTicle_name",
            field=models.CharField(max_length=255, null=True, verbose_name="剧本名"),
        ),
        migrations.AlterField(
            model_name="article",
            name="arTicle_score",
            field=models.IntegerField(max_length=11, null=True, verbose_name="剧本得分"),
        ),
        migrations.AlterField(
            model_name="article",
            name="arTicle_theme",
            field=models.CharField(max_length=255, null=True, verbose_name="剧本主题"),
        ),
    ]
